#!/usr/bin/env bash
# PhenoDP retrieve + Gemma-4-31B pp2prompt_v2 rerank on archive2 datasets (MyGene2 + AllG2P).
#
# Inputs (pre-filtered, in datasets/RareBench_min/data/):
#   MYGENE2.jsonl  — 131 cases (from 146 raw; filter: >=3 HPO, PhenoDP-compatible)
#   ALLG2P.jsonl   — 1771 cases (from 3829 raw; filter: >=3 HPO, PhenoDP-compatible,
#                    definitive/strong confidence only)
#
# PP2Prompt narratives generated by PP2Prompt/generate_archive2_merged_prompts.py
#   → PP2Prompt/prompts/archive2_merged_en/ (1902 files, named to match pipeline patient IDs)
#
# Prereq: vLLM API server running in screen "llm2" (google/gemma-4-31B-it on port 8001).
# Always writes to a NEW timestamped run dir — never overwrites existing results.

set -euo pipefail

PYTHON_BIN="/vol/home-vol3/wbi/elmoftym/.llmg4/bin/python"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PP2PROMPT_DIR="/vol/home-vol3/wbi/elmoftym/Mofty/PhenoPacket/PP2Prompt/prompts/archive2_merged_en"
TOKENIZER_PATH="/vol/home-vol3/wbi/elmoftym/.cache/huggingface/hub/models--google--gemma-4-31B-it/snapshots/439edf5652646a0d1bd8b46bfdc1d3645761a445"

cd "${SCRIPT_DIR}"

"${PYTHON_BIN}" run_rarebench_api_rerank.py \
  --run-name "phenodp_gemma4_archive2_pp2prompt_v2" \
  --data-dir "/vol/home-vol3/wbi/elmoftym/Mofty/PhenoPacket/datasets/RareBench_min/data" \
  --subsets "MYGENE2,ALLG2P" \
  --api-base "http://127.0.0.1:8001/v1" \
  --api-key "local-token" \
  --api-model "google/gemma-4-31B-it" \
  --max-tokens 400 \
  --retrieve-k 50 \
  --rerank-cutoffs 3,5,10 \
  --max-api-workers 16 \
  --prompt-version pp2prompt_v2 \
  --pp2prompt-dir "${PP2PROMPT_DIR}" \
  --method-prefix "reranker_gemma4" \
  --phenodp-device cpu \
  --use-completions \
  --tokenizer "${TOKENIZER_PATH}" \
  2>&1 | tee pr_gemma4_archive2_pp2prompt_v2.log
